#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'ClientApp/**/*.s+(a|c)ss'
  ignore:
    - './node_modules/**/*.*'
# Rule Configuration
rules:
  indentation:
    - 2
    - 
      size: 4
