//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wacton.Japangolin.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wacton.Japangolin.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1198180,会う,あう,to meet
        ///1381380,青,あお,blue
        ///1381390,青い,あおい,blue
        ///2013900,赤,あか,red
        ///1383240,赤い,あかい,red
        ///1532350,明い,あかるい,bright
        ///1332650,秋,あき,autumn
        ///1586270,開く,あく,&quot;to open,to become open&quot;
        ///1202450,開ける,あける,to open
        ///1352320,上げる,あげる,to give
        ///1428280,朝,あさ,morning
        ///1586330,朝御飯,あさごはん,breakfast
        ///1584640,,あさって,day after tomorrow
        ///1404630,足,あし,&quot;foot,leg&quot;
        ///1584660,明日,あした,tomorrow
        ///1000320,,あそこ,over there
        ///1542160,遊ぶ,あそぶ,&quot;to play,to make a visit&quot;
        ///1586420,暖かい,あたたかい,warm
        ///1582310,頭,あたま,head
        ///1361490,新しい,あたらしい,new
        ///1483185 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JLPT_N5 {
            get {
                return ResourceManager.GetString("JLPT_N5", resourceCulture);
            }
        }
    }
}
